### ISSUE TITLE
Tex files not downloading instantly

### ISSUE THREAD

**Issue by chessisdabest** [vEnhance/otis-web#336] opened 2024-02-04 14:04 UTC
**Describe the bug**
I cant download the tex templates.
**To Reproduce**
Just try to download it 

**Expected behavior**
Downloads a tex file like it used to

**Comment by vEnhance** [comment] 2024-02-04 14:33
can't repro

**Comment by chessisdabest** [comment] 2024-02-15 05:32
I got a screen recording

[screen-capture.webm](https://github.com/vEnhance/otis-web/assets/144521728/24658d06-1d7d-4d26-a56e-f117c6583f06)

**Comment by vEnhance** [comment] 2024-02-15 16:48
This is the intended behavior, just press Ctrl-S to save.

See https://discord.com/channels/740366393022742618/808946189457293319/1195041688335417375 for accompanying discussion.

Closing as wontfix.

**Closed by vEnhance** 2024-02-15 16:48 UTC
Labels: bug
